<a href="https://colab.research.google.com/github/joncalle/ML2/blob/main/Chrun.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [10]:
chr = pd.read_csv("https://raw.githubusercontent.com/joncalle/ML2/main/ChurnData.csv")
print(chr.shape) # print rows, columns
chr.head(10).T     # dump first 2 rows

(5630, 20)

,0,1,2,3,4,5,6,7,8,9
CustomerID,50001,50002,50003,50004,50005,50006,50007,50008,50009,50010
Churn,1,1,1,1,1,1,1,1,1,1
Tenure,4.0,NaN,NaN,0.0,0.0,0.0,NaN,NaN,13.0,NaN
PreferredLoginDevice,Mobile Phone,Phone,Phone,Phone,Phone,Computer,Phone,Phone,Phone,Phone
CityTier,3,1,1,3,1,1,3,1,3,1
WarehouseToHome,6.0,8.0,30.0,15.0,12.0,22.0,11.0,6.0,9.0,31.0
PreferredPaymentMode,Debit Card,UPI,Debit Card,Debit Card,CC,Debit Card,Cash on Delivery,CC,E wallet,Debit Card
Gender,Female,Male,Male,Male,Male,Female,Male,Male,Male,Male
HourSpendOnApp,3.0,3.0,2.0,2.0,NaN,3.0,2.0,3.0,NaN,2.0
NumberOfDeviceRegistered,3,4,4,4,3,5,3,3,4,5
PreferedOrderCat,Laptop & Accessory,Mobile,Mobile,Laptop & Accessory,Mobile,Mobile Phone,Laptop & Accessory,Mobile,Mobile,Mobile
SatisfactionScore,2,3,3,5,5,5,2,2,3,3
MaritalStatus,Single,Single,Single,Single,Single,Single,Divorced,Divorced,Divorced,Single
NumberOfAddress,9,7,6,8,3,2,4,3,2,2
Complain,1,1,1,0,0,1,0,1,1,0
OrderAmountHikeFromlastYear,11.0,15.0,14.0,23.0,11.0,22.0,14.0,16.0,14.0,12.0
CouponUsed,1.0,0.0,0.0,0.0,1.0,4.0,0.0,2.0,0.0,1.0
OrderCount,1.0,1.0,1.0,1.0,1.0,6.0,1.0,2.0,1.0,1.0
DaySinceLastOrder,5.0,0.0,3.0,3.0,3.0,7.0,0.0,0.0,2.0,1.0
CashbackAmount,160,121,120,134,130,139,121,123,127,123

In [7]:
#verify there are no missing values
chr.isna().sum()

CustomerID                       0
Churn                            0
Tenure                         264
PreferredLoginDevice             0
CityTier                         0
WarehouseToHome                251
PreferredPaymentMode             0
Gender                           0
HourSpendOnApp                 255
NumberOfDeviceRegistered         0
PreferedOrderCat                 0
SatisfactionScore                0
MaritalStatus                    0
NumberOfAddress                  0
Complain                         0
OrderAmountHikeFromlastYear    265
CouponUsed                     256
OrderCount                     258
DaySinceLastOrder              307
CashbackAmount                   0
dtype: int64

In [12]:
chr = chr.fillna(0)
chr.isnull().sum()

CustomerID                     0
Churn                          0
Tenure                         0
PreferredLoginDevice           0
CityTier                       0
WarehouseToHome                0
PreferredPaymentMode           0
Gender                         0
HourSpendOnApp                 0
NumberOfDeviceRegistered       0
PreferedOrderCat               0
SatisfactionScore              0
MaritalStatus                  0
NumberOfAddress                0
Complain                       0
OrderAmountHikeFromlastYear    0
CouponUsed                     0
OrderCount                     0
DaySinceLastOrder              0
CashbackAmount                 0
dtype: int64

In [13]:
for col in chr:
  print(chr[col].unique())

[50001 50002 50003 ... 55628 55629 55630]
[1 0]
[ 4.  0. 13. 11.  9. 19. 20. 14.  8. 18.  5.  2. 30.  1. 23.  3. 29.  6.
 26. 28.  7. 24. 25. 10. 15. 22. 27. 16. 12. 21. 17. 50. 60. 31. 51. 61.]
['Mobile Phone' 'Phone' 'Computer']
[3 1 2]
[  6.   8.  30.  15.  12.  22.  11.   9.  31.  18.  13.  20.  29.  28.
  26.  14.   0.  10.  27.  17.  23.  33.  19.  35.  24.  16.  25.  32.
  34.   5.  21. 126.   7.  36. 127.]
['Debit Card' 'UPI' 'CC' 'Cash on Delivery' 'E wallet' 'COD' 'Credit Card']
['Female' 'Male']
[3. 2. 0. 1. 4. 5.]
[3 4 5 2 1 6]
['Laptop & Accessory' 'Mobile' 'Mobile Phone' 'Others' 'Fashion' 'Grocery']
[2 3 5 4 1]
['Single' 'Divorced' 'Married']
[ 9  7  6  8  3  2  4 10  1  5 19 21 11 20 22]
[1 0]
[11. 15. 14. 23. 22. 16. 12.  0. 13. 17. 18. 24. 19. 20. 21. 25. 26.]
[ 1.  0.  4.  2.  9.  6. 11.  7. 12. 10.  5.  3. 13. 15.  8. 14. 16.]
[ 1.  6.  2. 15.  4.  7.  3.  9.  0. 11.  5. 12. 10.  8. 13. 14. 16.]
[ 5.  0.  3.  7.  2.  1.  8.  6.  4. 15.  9. 11. 10. 13. 12. 17. 16. 14.
 30. 46. 18. 31.]
[160 121 120 134 130 139 123 127 295 154 196 129 157 161 150 162 203 117
 146 207 142 173 190 143 133 209 122 194 126 299 125 187 131 111 205 137
 145 128 290 287 195 237 300 159 268 136 144 153 166 163 168 138 167 176
 149 204 185 200 225 236 189 222 206   0 179 188 124 132 292 261 291 164
 165 169 294 135 152 269 156 140 235 218 220 276 147 158 114 180 155 260
 112 221 148 219 271 240 175 151 293 283 215 171 183 181 197 267 243 232
 184 266 296 280 241 270 279 191 198 141 174 262 216 119 282 254 177 110
 113 186 212 248 217 238 211 284 116 272 228 202 263 208 249 178 274 214
 210 227 298 233 277 234 275 231 182 286 278 297 288 281 199 273 247 193
 264 192 201 244 252 170 229 230 258 115  12 118 289 239  56 320 324 315
 312 325 250  25 213 317 316 319 245 301 172 285 246 265 318 308 257 321
 305 304 223 307 242 309 253 323 302 259 256 311 303 322 313 306 224 226
 255  37 314  81]